# Generated by Django 6.0.6 on 2026-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='subsidy',
            field=models.PositiveIntegerField(default=0, verbose_name='津貼'),
        ),
    ]
