# Generated by Django 6.0.6 on 2026-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_workrecord_subsidy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
